### ISSUE TITLE
ucs2 - wrong endianness

### ISSUE THREAD

**Issue by andrewrk** [deoxxa/jsmc#20]
According to [wiki.vg](http://wiki.vg/Data_Types) strings are UCS-2 _big_ endian.

jsmc uses the [buffer api](http://nodejs.org/docs/latest/api/buffer.html#buffer_buffer) `ucs2` which is an alias to `utf16le`.

[Iconv](https://github.com/bnoordhuis/node-iconv) can do the necessary conversions.

**Comment by deoxxa** [comment]
Before using the `ucs2` string stuff, we reverse the byte order. It's cheap and (as far as I know) accurate. See the `mcstring16` methods on both the [parser](https://github.com/deoxxa/jsmc/blob/master/lib/parser.js#L49) and [serialiser](https://github.com/deoxxa/jsmc/blob/master/lib/serialiser.js#L11).

**Comment by andrewrk** [comment]
Sorry, I didn't realize that.

**Comment by deoxxa** [comment]
No problem! I'm happy someone is looking over the code, I'm sure there's a bunch of unclear/questionable things in there. :)
